# Generated by Django 3.2.4 on 2021-08-12 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiztaker',
            name='grade',
        ),
        migrations.AddField(
            model_name='quiztaker',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assessment.grade'),
        ),
        migrations.RemoveField(
            model_name='quiztaker',
            name='quiz',
        ),
        migrations.AddField(
            model_name='quiztaker',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assessment.quiz'),
        ),
    ]
