# Generated by Django 3.2.4 on 2021-09-17 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0012_auto_20210830_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/quiz_answers/', verbose_name='answer_file'),
        ),
    ]
