# Generated by Django 3.2.4 on 2021-09-22 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0013_question_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='score',
        ),
    ]
