# Generated by Django 3.2 on 2022-03-15 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_auto_20220311_0742'),
        ('assessment', '0016_quiz_timer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiztaker',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.student'),
        ),
    ]
