# Generated by Django 3.2 on 2022-03-20 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0017_alter_quiztaker_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
