# Generated by Django 3.2 on 2022-04-26 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0019_alter_quiz_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='update_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
