# Generated by Django 3.2 on 2022-06-02 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_auto_20220516_1109'),
        ('assessment', '0021_assignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='answer',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='max_score',
            field=models.FloatField(default=10.0),
        ),
        migrations.CreateModel(
            name='AssignmentTaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0)),
                ('completed', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_asignments', to='assessment.assignment')),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assessment.grade')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_asignments', to='user.student')),
            ],
            options={
                'verbose_name': 'QuizTaker',
                'verbose_name_plural': 'QuizTakers',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_responses', to='assessment.assignment')),
                ('assignment_taker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_responses', to='assessment.assignmenttaker')),
            ],
            options={
                'verbose_name': 'Response',
                'verbose_name_plural': 'Responses',
                'ordering': ['id'],
            },
        ),
    ]
