# Generated by Django 3.2 on 2022-06-07 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assessment', '0022_auto_20220602_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='supervisor',
            field=models.ForeignKey(default=1, limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, to='user.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignmentresponse',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/assignment_answers/', verbose_name='answer_file'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/assignment_questions/', verbose_name='answer_file'),
        ),
    ]
