# Generated by Django 3.2 on 2022-06-15 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0023_auto_20220607_0716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateField(),
        ),
    ]
