# Generated by Django 3.2 on 2022-06-22 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0025_auto_20220617_0657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='due_date',
        ),
    ]
