# Generated by Django 3.2.4 on 2021-09-22 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scope',
            old_name='programme',
            new_name='specialization',
        ),
    ]
