# Generated by Django 3.2.4 on 2021-09-25 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0003_rename_programme_scope_specialization'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='information',
            options={'ordering': ['id'], 'verbose_name': 'Information', 'verbose_name_plural': 'Information'},
        ),
        migrations.AlterModelOptions(
            name='informationimage',
            options={'ordering': ['id'], 'verbose_name': 'Information Image', 'verbose_name_plural': 'Information Images'},
        ),
        migrations.AlterModelOptions(
            name='notice',
            options={'ordering': ['id'], 'verbose_name': 'Notice', 'verbose_name_plural': 'Notices'},
        ),
        migrations.AlterModelOptions(
            name='scope',
            options={'ordering': ['id'], 'verbose_name': 'Scope', 'verbose_name_plural': 'Scopes'},
        ),
    ]
