# Generated by Django 3.2 on 2022-04-25 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0004_auto_20210925_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scope',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
