# Generated by Django 3.2 on 2022-04-26 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0005_alter_scope_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scope',
            old_name='departmment',
            new_name='department',
        ),
    ]
