# Generated by Django 3.2 on 2022-06-07 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0007_auto_20220525_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scope',
            name='is_general',
            field=models.BooleanField(default=False),
        ),
    ]
