# Generated by Django 3.2.4 on 2021-08-12 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicdata',
            options={'verbose_name': 'AcademicData', 'verbose_name_plural': 'AcademicData'},
        ),
        migrations.AlterModelOptions(
            name='courseregistration',
            options={'verbose_name': 'CourseRegistration', 'verbose_name_plural': 'CourseRegistrations'},
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='blood_group',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='genotype',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
