# Generated by Django 3.2.4 on 2021-08-17 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_alter_programme_max_level'),
        ('user', '0002_auto_20210812_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicdata',
            name='programme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.programme'),
        ),
    ]
