# Generated by Django 3.2.4 on 2021-09-18 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210817_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='is_course_adviser',
            field=models.BooleanField(default=False),
        ),
    ]
