# Generated by Django 3.2.4 on 2021-09-18 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_alter_programme_options'),
        ('user', '0006_staff_is_course_adviser'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseAdviser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.department')),
                ('level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.level')),
                ('staff', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, to='user.staff')),
            ],
        ),
    ]
