# Generated by Django 3.2 on 2021-07-05 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_biodata_matric_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familydata',
            old_name='guardian_phone',
            new_name='guardian_phone1',
        ),
        migrations.RenameField(
            model_name='familydata',
            old_name='next_of_kin_phone',
            new_name='guardian_phone2',
        ),
        migrations.AddField(
            model_name='academicdata',
            name='faculty',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='familydata',
            name='next_of_kin_phone1',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='familydata',
            name='next_of_kin_phone2',
            field=models.CharField(default='', max_length=300),
        ),
    ]
