# Generated by Django 3.2.4 on 2021-09-25 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20210922_1902'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicdata',
            options={'ordering': ['id'], 'verbose_name': 'AcademicData', 'verbose_name_plural': 'AcademicData'},
        ),
        migrations.AlterModelOptions(
            name='academichistory',
            options={'ordering': ['id'], 'verbose_name': 'AcademicHistory', 'verbose_name_plural': 'AcademicHistory'},
        ),
        migrations.AlterModelOptions(
            name='biodata',
            options={'ordering': ['id'], 'verbose_name': 'Biodata', 'verbose_name_plural': 'Biodata'},
        ),
        migrations.AlterModelOptions(
            name='courseregistration',
            options={'ordering': ['id'], 'verbose_name': 'CourseRegistration', 'verbose_name_plural': 'CourseRegistrations'},
        ),
        migrations.AlterModelOptions(
            name='familydata',
            options={'ordering': ['id'], 'verbose_name': 'FamilyData', 'verbose_name_plural': 'FamilyData'},
        ),
        migrations.AlterModelOptions(
            name='healthdata',
            options={'ordering': ['id'], 'verbose_name': 'HealthData', 'verbose_name_plural': 'HealthData'},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'ordering': ['id'], 'verbose_name': 'Staff', 'verbose_name_plural': 'Staff'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['id'], 'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['id'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
