# Generated by Django 3.2.4 on 2021-09-25 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0011_alter_session_options'),
        ('user', '0009_auto_20210925_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseregistration',
            name='semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.semester'),
        ),
        migrations.AlterField(
            model_name='courseregistration',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.session'),
        ),
    ]
