# Generated by Django 3.2.4 on 2021-07-22 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_alter_biodata_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biodata',
            name='email',
            field=models.EmailField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='first_name',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='last_name',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='local_govt',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='marital_status',
            field=models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced')], default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='matric_no',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='middle_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='nationality',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='permanent_address',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='religion',
            field=models.CharField(choices=[('Christianity', 'Christianity'), ('Islam', 'Islam'), ('Other', 'Other')], default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='state_of_origin',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_data', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='matric_no',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='user',
            name='middle_name',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterModelTable(
            name='academicdata',
            table=None,
        ),
        migrations.AlterModelTable(
            name='biodata',
            table=None,
        ),
        migrations.AlterModelTable(
            name='familydata',
            table=None,
        ),
        migrations.AlterModelTable(
            name='healthdata',
            table=None,
        ),
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
