# Generated by Django 3.2.4 on 2021-10-05 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0012_session_is_current'),
        ('user', '0011_auto_20211005_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicdata',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.level'),
        ),
    ]
