# Generated by Django 3.2.4 on 2021-10-22 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0014_alter_recommendedcourses_options'),
        ('user', '0012_academicdata_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='result',
            options={'ordering': ['id'], 'verbose_name': 'Result', 'verbose_name_plural': 'Results'},
        ),
        migrations.AddField(
            model_name='student',
            name='specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='academics.specialization'),
        ),
    ]
