# Generated by Django 3.2 on 2022-01-25 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0015_auto_20220125_2238'),
        ('user', '0013_auto_20211022_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='academics.specialization'),
        ),
    ]
