# Generated by Django 3.2 on 2022-03-11 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0016_auto_20220304_0719'),
        ('user', '0016_alter_staff_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseadviser',
            name='specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='academics.specialization'),
        ),
        migrations.AlterField(
            model_name='courseadviser',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.department'),
        ),
    ]
