# Generated by Django 3.2 on 2022-03-16 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_auto_20220311_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biodata',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='local_govt',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='permanent_address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='phone_no_1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='state_of_origin',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
