# Generated by Django 3.2 on 2022-03-18 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_auto_20220316_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicdata',
            name='qualification',
            field=models.CharField(choices=[('B.Sc', 'B.Sc'), ('M.Sc', 'M.Sc'), ('Other', 'Other')], default='Other', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='academichistory',
            name='qualification_earned',
            field=models.CharField(choices=[('JSSCE', 'JSSCE'), ('SSCE', 'SSCE'), ('Bachelors', 'Bachelors'), ('Other', 'Other')], default='Other', max_length=250, null=True),
        ),
    ]
