# Generated by Django 3.2 on 2022-04-25 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_auto_20220318_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthdata',
            name='STIs',
            field=models.TextField(blank=True, null=True),
        ),
    ]
