# Generated by Django 3.2 on 2022-04-26 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_alter_healthdata_stis'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='update_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='update_timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='result',
            name='updated',
            field=models.BooleanField(default=False),
        ),
    ]
