# Generated by Django 3.2 on 2022-06-23 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_auto_20220516_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthdata',
            name='diabetes',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
