# Generated by Django 3.2 on 2022-06-24 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_alter_healthdata_diabetes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
    ]
