# Generated by Django 3.2.4 on 2021-09-22 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_alter_programme_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programme',
            options={'verbose_name': 'Programme', 'verbose_name_plural': 'Programmes'},
        ),
    ]
