# Generated by Django 3.2.4 on 2021-09-22 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0003_rename_programme_scope_specialization'),
        ('user', '0008_auto_20210922_1902'),
        ('academics', '0007_alter_programme_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Programme',
            new_name='Specialization',
        ),
        migrations.AlterModelOptions(
            name='specialization',
            options={'verbose_name': 'Specialization', 'verbose_name_plural': 'Specializations'},
        ),
        migrations.RenameField(
            model_name='course',
            old_name='programme',
            new_name='specialization',
        ),
    ]
