# Generated by Django 3.2.4 on 2021-09-25 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_auto_20210922_1902'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField(choices=[(1, '1st Semester'), (2, '2nd Semester')], default=1, null=True)),
            ],
            options={
                'verbose_name': 'Semester',
                'verbose_name_plural': 'Semesters',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['id'], 'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['id'], 'verbose_name': 'Department', 'verbose_name_plural': 'Departments'},
        ),
        migrations.AlterModelOptions(
            name='faculty',
            options={'ordering': ['id'], 'verbose_name': 'Faculty', 'verbose_name_plural': 'Faculty'},
        ),
        migrations.AlterModelOptions(
            name='level',
            options={'ordering': ['id'], 'verbose_name': 'Level', 'verbose_name_plural': 'Levels'},
        ),
        migrations.AlterModelOptions(
            name='specialization',
            options={'ordering': ['id'], 'verbose_name': 'Specialization', 'verbose_name_plural': 'Specializations'},
        ),
    ]
