# Generated by Django 3.2.4 on 2021-09-25 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_session'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['year'], 'verbose_name': 'Session', 'verbose_name_plural': 'Sessions'},
        ),
    ]
