# Generated by Django 3.2.4 on 2021-10-06 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0012_session_is_current'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendedCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses', models.ManyToManyField(to='academics.Course')),
                ('level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.level')),
                ('semester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.semester')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_courses', to='academics.specialization')),
            ],
            options={
                'verbose_name': 'RecommendedCourses',
                'verbose_name_plural': 'RecommendedCourses',
            },
        ),
    ]
