# Generated by Django 3.2.4 on 2021-10-22 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0013_recommendedcourses'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recommendedcourses',
            options={'ordering': ['id'], 'verbose_name': 'RecommendedCourses', 'verbose_name_plural': 'RecommendedCourses'},
        ),
    ]
