# Generated by Django 3.2 on 2022-01-25 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0014_alter_recommendedcourses_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['-year'], 'verbose_name': 'Session', 'verbose_name_plural': 'Sessions'},
        ),
        migrations.AlterField(
            model_name='session',
            name='year',
            field=models.CharField(max_length=4, unique=True),
        ),
    ]
