# Generated by Django 3.2 on 2022-03-18 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0016_auto_20220304_0719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='code',
            field=models.IntegerField(choices=[(100, 'One'), (200, 'Two'), (300, 'Three'), (400, 'Four'), (500, 'Five')], default=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='semester',
            name='semester',
            field=models.IntegerField(choices=[(1, '1st Semester'), (2, '2nd Semester')], default=1, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='year',
            field=models.CharField(default=2022, max_length=4, unique=True),
        ),
    ]
