# Generated by Django 3.2 on 2022-03-18 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0017_auto_20220318_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='year',
            field=models.CharField(default='2022', max_length=4, unique=True),
        ),
    ]
