# Generated by Django 3.2 on 2022-03-19 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0018_alter_session_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendedcourses',
            name='source_specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direct_recommended_courses', to='academics.specialization'),
        ),
    ]
