# Generated by Django 3.2 on 2022-05-31 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0019_recommendedcourses_source_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='unit',
            field=models.IntegerField(default=2),
        ),
    ]
