# Generated by Django 3.2 on 2022-06-20 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0020_course_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
    ]
